### ISSUE TITLE
Travis als submodule

### ISSUE THREAD

**Issue by dav1d-wright** [HSR-Stud/Willkommen#1]
Ich finde, hier sollte Travis als Submodule eingebunden werden, und das `HowTo-Travis.md` sollte das `README.MD` vom Travis Repo includen (z.b. durch {{some_other_file.txt}}), damit diese nicht auseinanderlaufen.

**Comment by pescara** [comment]
Ausgeführt:
- Travis sowohl hier im Willkommens-Repo als auch im VorlageZFLatex als Submodule eingefügt
- README aus Travis in HowTo-Travis.md kopiert -> Includen mit einem weiteren Link fand ich nicht so sinnvoll, denn diese Repo soll ja "zentrale Anlaufstelle" sein.
Passt das so für euch?
Vorschlag:
- README aus Travis künftig löschen

**Comment by dav1d-wright** [comment]
@pescara Ja da hast du recht, jedoch wird Travis ja "thematisch" im Travis-Repo verwaltet, deshalb fände ich es nicht sinnvoll, wenn dort das Readme gelöscht wird.  Z.B. könnte es sein, dass man eher beim Travis-Repo nach einem Readme schauen, wenn man Probleme hat. 

Ich finde hierbei zwei Punkte sehr wichtig:
- Jedes Repo soll ein Readme haben
- Ein Thema soll nur an einer Stelle verwaltet werden, i.e. "no duplicate code"

Ausserdem wird das Travis-Repo ständig als submodule in anderen Repos verwendet, jedoch wird das Willkommen-Repo nirgendwo sonst verwendet, und erst recht nie mehr ohne Travis als submodule.

Deshalb würde ich lieber den Inhalt vom Travis `README.MD` includen in `HowTo-Travis.md`. Ich denke das wäre am saubersten, da es all diese Punkte löst.

Danke fürs behandeln dieses Issues!

**Comment by pescara** [comment]
Erledigt:-)

**Comment by dav1d-wright** [comment]
Merci :)
