### ISSUE TITLE
TeXLive und TeXlipse beschreibung hinzufügen.

### ISSUE THREAD

**Issue by dav1d-wright** [HSR-Stud/Willkommen#2]
Ich würde hier noch eine Beschreibung für TeXlipse und TexLive hinzufügen. Für Nueinsteiger, die häufig schon Erfahrung mit Eclipse haben, war es sehr hilfreich, dass man einfach ein bestehendes Projekt clonen und dann in Eclipse importieren konnte.

**Comment by pescara** [comment]
Hi wrd90
Könnte du dir vorstellen dazu gleich einen Post zu schreiben?

**Comment by dav1d-wright** [comment]
Ja kann ich gerne machen.

**Comment by dav1d-wright** [comment]
Done :)
